-- liquibase formatted sql
--changeset tsarkoff:001 failOnError:true


create table public.users
(
    id               bigint generated by default as identity primary key,
    username         varchar(64)  not null,
    password         varchar(255) not null,
    enabled          boolean               default true,
    auth_token       varchar(255) not null default '',
    role_id          bigint       not null,
    create_dt        timestamp             default current_timestamp,
    last_activity_dt timestamp             default current_timestamp
);

create table public.authorities
(
    username_id bigint,
    username    varchar(50) not null,
    authority   varchar(50) not null,
    constraint fk_authorities_users foreign key (username_id) references users (id)
--  constraint fk_authorities_users foreign key (username) references users (username)
);
create unique index ix_auth_username on public.authorities (username, authority);

create table public.roles
(
    id   bigint generated by default as identity primary key,
    role varchar(64) not null
);

alter table public.users
    add constraint fk_user_role_id foreign key (role_id) references roles (id) on update restrict deferrable initially deferred;

create table public.permissions
(
    id         bigint generated by default as identity primary key,
    permission varchar(32) not null
);

create table public.roles_permissions
(
    role_id       bigint not null,
    permission_id bigint not null
);

alter table public.roles_permissions
    add primary key (role_id, permission_id),
    add constraint fk_role_id foreign key (role_id) references roles (id) on update restrict deferrable initially deferred,
    add constraint fk_permission_id foreign key (permission_id) references permissions (id) on update restrict deferrable initially deferred;

-- update public.cart set price = 100;
--rollback drop table contacts.customers;
